In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sn
sn.set()

In [2]:
data =  pd.read_csv("1.02. Multiple linear regression.csv")
data

     SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
5   1670  2.91           1
6   1764  3.00           2
7   1764  3.00           1
8   1792  3.01           2
9   1850  3.01           3
10  1735  3.02           3
11  1775  3.07           2
12  1735  3.08           1
13  1712  3.08           3
14  1773  3.12           2
15  1872  3.17           2
16  1755  3.17           3
17  1674  3.17           2
18  1842  3.17           3
19  1786  3.19           3
20  1761  3.19           3
21  1722  3.19           3
22  1663  3.20           3
23  1687  3.21           1
24  1974  3.24           1
25  1826  3.28           1
26  1787  3.28           1
27  1821  3.28           3
28  2020  3.28           1
29  1794  3.28           2
..   ...   ...         ...
54  1879  3.44           1
55  1887  3.47           1
56  1730  3.47           2
57  1953  3.47           1
58  1781  3.47           2
59  1891  3.48           2
60  1964  3.49           1
61  1808  3.49           3
62  1893  3.50           3
63  2041  3.51           3
64  1893  3.51           1
65  1832  3.52           2
66  1850  3.52           3
67  1934  3.54           2
68  1861  3.58           2
69  1931  3.58           3
70  1933  3.59           3
71  1778  3.59           1
72  1975  3.60           1
73  1934  3.60           3
74  2021  3.61           3
75  2015  3.62           3
76  1997  3.64           1
77  2020  3.65           2
78  1843  3.71           3
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [3]:
data.describe

<bound method NDFrame.describe of      SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
5   1670  2.91           1
6   1764  3.00           2
7   1764  3.00           1
8   1792  3.01           2
9   1850  3.01           3
10  1735  3.02           3
11  1775  3.07           2
12  1735  3.08           1
13  1712  3.08           3
14  1773  3.12           2
15  1872  3.17           2
16  1755  3.17           3
17  1674  3.17           2
18  1842  3.17           3
19  1786  3.19           3
20  1761  3.19           3
21  1722  3.19           3
22  1663  3.20           3
23  1687  3.21           1
24  1974  3.24           1
25  1826  3.28           1
26  1787  3.28           1
27  1821  3.28           3
28  2020  3.28           1
29  1794  3.28           2
..   ...   ...         ...
54  1879  3.44           1
55  1887  3.47           1
56  1730  3.47           2
57  1953  3.47           1
58  1781  3.47           2
59  1891  3.48           2
60  1964  3.49           1
61  1808  3.49           3
62  1893  3.50           3
63  2041  3.51           3
64  1893  3.51           1
65  1832  3.52           2
66  1850  3.52           3
67  1934  3.54           2
68  1861  3.58           2
69  1931  3.58           3
70  1933  3.59           3
71  1778  3.59           1
72  1975  3.60           1
73  1934  3.60           3
74  2021  3.61           3
75  2015  3.62           3
76  1997  3.64           1
77  2020  3.65           2
78  1843  3.71           3
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]>

In [4]:
y = data['GPA']
x1 = data[['SAT', 'Rand 1,2,3']]

In [ ]:
x1 = sm.add_constant(x1)
results = sm.OLS(y,x1).fit()
results.summary()